# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\x12\x08zb_stats\"\x1c\n\x0cStatsRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\"^\n\tStatsItem\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0e\n\x06istat1\x18\x02 \x01(\x05\x12\x0e\n\x06istat2\x18\x03 \x01(\x05\x12\x0e\n\x06\x66stat1\x18\x04 \x01(\x02\x12\x0e\n\x06\x66stat2\x18\x05 \x01(\x02\"\x7f\n\nStatsReply\x12.\n\x05stats\x18\x01 \x03(\x0b\x32\x1f.zb_stats.StatsReply.StatsEntry\x1a\x41\n\nStatsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.zb_stats.StatsItem:\x02\x38\x01\x32I\n\x0bStatsReport\x12:\n\x08GetStats\x12\x16.zb_stats.StatsRequest\x1a\x14.zb_stats.StatsReply\"\x00\x42(\n\x10io.grpc.zb_statsB\x0cZBStatsProtoP\x01\xa2\x02\x03ZBSb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020io.grpc.zb_statsB\014ZBStatsProtoP\001\242\002\003ZBS'
  _globals['_STATSREPLY_STATSENTRY']._loaded_options = None
  _globals['_STATSREPLY_STATSENTRY']._serialized_options = b'8\001'
  _globals['_STATSREQUEST']._serialized_start=25
  _globals['_STATSREQUEST']._serialized_end=53
  _globals['_STATSITEM']._serialized_start=55
  _globals['_STATSITEM']._serialized_end=149
  _globals['_STATSREPLY']._serialized_start=151
  _globals['_STATSREPLY']._serialized_end=278
  _globals['_STATSREPLY_STATSENTRY']._serialized_start=213
  _globals['_STATSREPLY_STATSENTRY']._serialized_end=278
  _globals['_STATSREPORT']._serialized_start=280
  _globals['_STATSREPORT']._serialized_end=353
# @@protoc_insertion_point(module_scope)
